# Generated by Django 3.1.2 on 2020-10-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='deleteYn',
            field=models.BooleanField(default=False),
        ),
    ]
